# Generated by Django 4.2.3 on 2023-08-10 02:44

from django.db import migrations
from django.conf import settings

from app.accounts.models import User


def create_root_user(apps, schema_editor):
    User.objects.create_superuser(
        **settings.ROOT_USER,
    )


def delete_root_user(apps, schema_editor):
    User.objects.filter(
        email=settings.ROOT_USER["email"],
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_root_user,
            delete_root_user,
        ),
    ]
