# Generated by Django 4.2.3 on 2023-08-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('beach', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SharkAttack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Invalid', 'Invalid'), ('Unprovoked', 'Unprovoked'), ('Provoked', 'Provoked'), ('Sea Disaster', 'Sea Disaster')], default='Invalid')),
                ('country', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=255)),
                ('victim_name', models.CharField(max_length=255)),
                ('victim_gender', models.CharField(max_length=10)),
                ('victim_age', models.SmallIntegerField()),
                ('victim_injury', models.CharField(max_length=255)),
                ('fatal', models.BooleanField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('species', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
